# Generated by ./update.sh - do not update manually!
# Last updated: 2025-12-16
{fetchurl}:
let
  any-darwin = {
    version = "6.9.80-2025-09-04";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Mac/QQ_6.9.80_250904_01.dmg";
      hash = "sha256-VUjgWQIxabjXkXJhxQiQJlYDkbLDNLaVQeRaZ4WGOIs=";
    };
  };
in {
  aarch64-darwin = any-darwin;
  x86_64-darwin = any-darwin;
  aarch64-linux = {
    version = "3.2.22-2025-12-03";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.22_251203_arm64_01.deb";
      hash = "sha256-3HBpnLkO/an/E876Q0A2mG5JNBafxUdm33DL6KLjeZk=";
    };
  };
  x86_64-linux = {
    version = "3.2.22-2025-12-03";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.22_251203_amd64_01.deb";
      hash = "sha256-PwBL2yRrMZTSdsY26pbLQKfguBP+pHCVfRMx6AMyvVQ=";
    };
  };
}
