# Generated by ./update.sh - do not update manually!
# Last updated: 2025-11-05
{fetchurl}:
let
  any-darwin = {
    version = "6.9.82-2025-10-23";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Mac/QQ_6.9.82_251023_01.dmg";
      hash = "sha256-oBhThy9NC0W6gyztHQCL88NDdQrYHzZ27RAzTGcyyRY=";
    };
  };
in {
  aarch64-darwin = any-darwin;
  x86_64-darwin = any-darwin;
  aarch64-linux = {
    version = "3.2.19-2025-08-20";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.19_250820_arm64_01.deb";
      hash = "sha256-rHgN0T9lcoAucwR3B2U8so/dAUfB92dQYc0TncTHPaM=";
    };
  };
  x86_64-linux = {
    version = "3.2.19-2025-08-20";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.19_250820_amd64_01.deb";
      hash = "sha256-4Y0GSWwFkqYX5ezE2Jk/tZIwsBHg88ZxJghzB+kXTds=";
    };
  };
}
