# Generated by ./update.sh - do not update manually!
# Last updated: 2025-11-06
{fetchurl}:
let
  any-darwin = {
    version = "6.9.82-2025-10-23";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Mac/QQ_6.9.82_251023_01.dmg";
      hash = "sha256-oBhThy9NC0W6gyztHQCL88NDdQrYHzZ27RAzTGcyyRY=";
    };
  };
in {
  aarch64-darwin = any-darwin;
  x86_64-darwin = any-darwin;
  aarch64-linux = {
    version = "3.2.18-2025-07-10";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.18_250710_arm64_01.deb";
      hash = "sha256-37HEXpLyeIjgXsAonNjS3YaIwk4It2LDy6Yj4lqK94Q=";
    };
  };
  x86_64-linux = {
    version = "3.2.18-2025-07-10";
    src = fetchurl {
      url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/Linux/QQ_3.2.18_250710_amd64_01.deb";
      hash = "sha256-P023rIalPAgBXZqJvnCgEHqTumWm+dhaUefzuR/4aoU=";
    };
  };
}
